### ISSUE TITLE
generateIdentityKeyPair() returning special characters key pair

### ISSUE THREAD

**Issue by usafhassanintouch** [elsehow/signal-protocol#8]
Hello,

I am using signal-protocol in my express project. The issue that I am facing is that the generateIdentityKeyPair() method returns identity key pair (pubKey, privKey) in form of an array buffer which is fine.
But i need to store them somewhere on client end and I want to convert them to string format (base64)
 but when i try to do so, i get non-readable ascii characters like this : ♣X�WQ�]�J�dF�♦�l-w>̪���g>���U�!
I have tried ab2str and a few similar methods to convert them into proper keys but still no luck.
Any guidance would be highly appreciated. Thanks

**Comment by elsehow** [comment]
I think this question is a little outside of this package's scope, but since this library uses [protobufjs^5.0.1](https://github.com/dcodeIO/protobuf.js/tree/ProtoBuf5), maybe you could look there for ideas.

Please feel free to re-open this issue if you believe there's a problem on this package's end.
